# This is a basic workflow to help you get started with Actions
name: Injection Test

# Run workflow when issue is opened
on: 
  issues:
  push:
  issue_comment:
  pull_request:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: CI 7-1. Push 전용 성공 메시지 전송
         run: |
          echo "${{ github.event.head_commit.committer.name }}"
