# This is a basic workflow to help you get started with Actions
name: Injection Test

# Run workflow when issue is opened
on: 
  issues:
  issue_comment:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send Notification
        run: |
          echo "CURRENT_BRANCH=$(echo $([ -z '${{ github.event.pull_request.title }}' ]))" >> $GITHUB_ENV
          echo '${{ github.ACTOR }}'
          echo '${{ github.HEAD_REF }}'
          echo '${{ github.REF }}'
          echo '${{ github.REF_NAME }}'
          echo '${{ github.event.comment }}'
          echo '${{ github.event.comment.body }}'
          echo '${{ github.event.comment.user.login }}'
          echo '${{ github.event.commits }}'
          echo "Done"
