name: Pure js bug

on:
  issues:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step0
        uses: 94dreamer/create-report@main
        with:
          type: close
          wxhook: https://www.africau.edu/images/default/sample.pdf
