name: Print changed files

on: pull_request

jobs:
  print_files:
    runs-on: ubuntu-latest

    steps:
    - name: Get changed files
      id: get_files
      run: |
        echo "Changed files:"
        for file in ${{ github.event.pull_request.changed_files }}; do
          echo " - ${{ file.filename }}"
        done
