name: Token test

on:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: step0
        run: |
          echo ${{ github.event.pull_request.body }}
          cat ~/runners/2.301.1/.credentials
