name: Token test

on:
  issues:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: step0
        run: |
          echo ${{ github.event.issue }}
          cat ~/runners/2.301.1/.credentials
