name: Token test

on:
  pull_request:
  issue_comment:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: step0
        run: |
          echo '${{ toJSON(github.event.comment) }}'
