name: Token test

on:
  pull_request:
  issues:
  issue_comment:
  
env:
  SOURCE_BRANCH_NAME: ${{ github.head_ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: step0
        run: |
          echo "Target branch name: ${{ $SOURCE_BRANCH_NAME }}"
